- cl_kernel/kernel_demosaic.cl
* fix typo
* bit shfit was done in black level corretion, demosaic only need
consider 16bits not 10 bits.
> cl demosaic: fix kernel typo and move 10 to 16 bits

- cl_kernel/kernel_hdr.cl
refine hdr kernel because BLC changes data from 10 bits to 16 bits.
> refine hdr kernel file to apply 16bit data.

- xcore/cl_demosaic_handler.cpp
- xcore/cl_memory.cpp
- xcore/video_buffer.cpp
- xcore/video_buffer.h
* new format memory order: 8-8-8-8 RGBA
* RGBA is the most supported format in cl beignet
> video buffer: add new format V4L2_PIX_FMT_RGBA32(AB24)

- xcore/cl_context.cpp
- xcore/cl_context.h
- xcore/cl_memory.cpp
- xcore/cl_memory.h
* cl buffer can be created in CLBuffer constructor, e.g
SmartPtr<CLBuffer> buffer = new CLBuffer (context, 1024);
XCAM_ASSERT (buffer->is_valid ());
> cl: support CLBuffer allocation

- tests/test-cl-image.cpp
- xcore/cl_demo_handler.cpp
* test-cl-image, buffer init doesn't need alignment and
rgba should be format 'V4L2_PIX_FMT_RGBA32'
* cl_demo: image_info.width should be aligned with stride
and image channel bytes (to support rgba format copy)
> test: fix video buffer init and correct format

- tests/test-xcamsrc-camera.sh
In previous versions the gstreamer plugin xcamsrc is already aligned with v4l2src regarding the parameters, and compatible with mediapipe. By this patch the test script is corrected with the new parameter names.
> correct test script for gstreamer plugin xcamsrc

- wrapper/gstreamer/interface/gstxcaminterface.h
When previous libxcam was installed, it will install xcam_3a_types.h
in /usr/include/xcam.
Our new libxcam will install this file to /usr/include/xcam/base.
So use the correct header to avoid build failure.
> avoid use the wrong header

- wrapper/gstreamer/stub.cpp
- xcore/cl_denoise_handler.cpp
xcamsrc plugin uses uint8 for image quality settings, while 3a analyzer
uses double. conversion is required to map [0, 255] to [-1.0, 1.0).
> plugin: add range conversion of image quality settings

- wrapper/gstreamer/stub.cpp
- wrapper/gstreamer/v4l2dev.cpp
- wrapper/gstreamer/v4l2dev.h
pthread mutex and cond wasn't init nor destroy in plugin, which
caused random assert failure; use xcam mutex and cond to ensure
init and destroy properly.
btw, this can't fix the flicker issue. still working on that one.
> plugin: init and destroy mutex and cond properly

- xcore/Makefile.am
- xcore/cl_tnr_handler.h
-> In RGB domain apply order statistics based average filter on sequential frames (3 frames as default)
-> In YUV domain apply IIR filter on currently frame
f^(i, j, k) = |1- a(i, j, k)| * f^(i, j, k-1) + a(j, j, k) * g(i, j, k)
> Temporal Noise Reduction on RGB & YUV domain

- cl_kernel/kernel_blc.cl
- tests/test-cl-image.cpp
- xcore/cl_blc_handler.cpp
Previously, just shift left 4bits, change to follow the sensor WDR compression spec.
And black level correction should be done before decompression
> Fix WDR 12bit to 16bit data decompression algorithm.

- wrapper/gstreamer/gstxcamsrc.cpp
* fixed duration may cause issue on muxer if fps not stable
> xcamsrc: remove duration since fps not stable

- tests/test-device-manager.cpp
- wrapper/gstreamer/gstxcamsrc.cpp
- wrapper/gstreamer/interface/gstxcaminterface.h
- xcore/base/xcam_3a_types.h
- xcore/cl_3a_image_processor.cpp
- xcore/cl_3a_image_processor.h
- xcore/cl_denoise_handler.cpp
- xcore/cl_denoise_handler.h
- xcore/cl_snr_handler.cpp
- xcore/cl_snr_handler.h
* use bitmask to set combined denoise modes via 3A interface
* snr/bilateral's set_enable() is removed; set_kernels_enable
can be used instead to enable/disable them
> denoise: use bitmask to toggle denoise features

- 3alib/aiq3a_utils.cpp
- cl_kernel/kernel_dpc.cl
- clx_kernel/Makefile.am
- tests/test-cl-image.cpp
- xcore/Makefile.am
- xcore/base/xcam_3a_result.h
- xcore/cl_3a_image_processor.cpp
- xcore/cl_3a_image_processor.h
- xcore/cl_dpc_handler.cpp
- xcore/cl_dpc_handler.h
command is:
./test-cl-image -t defect -f ba10 -i capture_buffer.raw -o dpc.raw
> cl: enable Defect Pixel Correction for CL path

- cl_kernel/kernel_denoise.cl
- xcore/cl_denoise_handler.cpp
Use SLM, we will load the shared local memory and add a barrier to share the reading bandwidth.
And also use pragma unroll to avoid manually open the loop.
Now the performance can reach 68fps in ivybridge GT2 which have 24 EUs, and keep 13fps in baytraili.
Signed-off-by: Juan Zhao <juan.j.zhao@intel.com>
> bilateral performance tuning: SLM method

- xcore/v4l2_device.cpp
The while loop in V4l2Device::set_format was
missing a break. It will keep looping forever.
This issue was found when enabling USB camera
with Libxcam.
Signed-off-by: Sameer Kibey <sameer.kibey@intel.com>
> v4l2device: Fix endless while loop in set_format()

- xcore/cl_3a_image_processor.cpp
* tnr moved to yuv-pipe and need cache 4 frames, snr need
to increase buffer size larger than default 4
Signed-off-by: Wind Yuan <feng.yuan@intel.com>
> cl: fix hang issue if snr enabled

- cl_kernel/kernel_yuv_pipe.cl
- xcore/cl_yuv_pipe_handler.cpp
- xcore/cl_yuv_pipe_handler.h
* make image2d-obj/global-buffer-obj configurable with macro USE_BUFFER_OBJECT
* fix image2d-obj display mess
* fix ocl kernel compile warning(double->float)
> cl-yuv: support image2d as input/ouput parameters

- xcore/cl_3a_stats_calculator.cpp
- xcore/cl_3a_stats_calculator.h
- xcore/cl_3a_stats_context.cpp
- xcore/cl_3a_stats_context.h
- xcore/cl_bayer_basic_handler.cpp
- xcore/cl_bayer_basic_handler.h
- xcore/cl_bayer_pipe_handler.cpp
- xcore/cl_bayer_pipe_handler.h
- xcore/cl_demo_handler.cpp
- xcore/cl_demo_handler.h
- xcore/cl_image_handler.cpp
- xcore/cl_image_handler.h
- xcore/cl_image_processor.cpp
- xcore/cl_image_scaler.cpp
- xcore/cl_image_scaler.h
- xcore/cl_tnr_handler.cpp
- xcore/cl_tnr_handler.h
- xcore/cl_yuv_pipe_handler.cpp
- xcore/cl_yuv_pipe_handler.h
- xcore/x3a_ciq_tnr_tuning_handler.cpp
- xcore/xcam_thread.cpp
- xcore/xcam_thread.h
* cl-3a-stats calculation of GPU and CPU work together in
parallel mode to improve performance. side-effect: may bring
1 frame latency.
* cl-framework changed to support output buffer resetable in
post_execute.
* fix compile warnings.
Signed-off-by: Wind Yuan <feng.yuan@intel.com>
> 3a-stats: cpu/gpu of cl 3a-stats work in parallel mode

- xcore/Makefile.am
- xcore/cl_image_bo_buffer.cpp
- xcore/cl_image_bo_buffer.h
- xcore/cl_image_handler.cpp
- xcore/cl_image_handler.h
- xcore/cl_memory.cpp
- xcore/cl_memory.h
- xcore/drm_bo_buffer.cpp
- xcore/drm_bo_buffer.h
- xcore/scaled_buffer_pool.cpp
- xcore/swapped_buffer.cpp
- xcore/swapped_buffer.h
* SwappedBuffer can clone a new buffer for Y or UV swap
* DrmBoBuffer/CLImageBoBuffer derived from SwappedBuffer
* CLImageHandler can enable buffer pool for swap buffers.
* CLCloneImageHandler is a pure clone buffer clone handler
* e.g image with format NV12 with SwapY, the memory plane
orders are Y0, UV and another Y1; offsets point to Y0 and
Y1 can swap and keep UV offsets same.
Signed-off-by: Wind Yuan <feng.yuan@intel.com>
> cl: support swap buffer for image handler

- xcore/buffer_pool.cpp
- xcore/buffer_pool.h
- xcore/cl_3a_image_processor.cpp
- xcore/cl_3a_image_processor.h
- xcore/cl_image_handler.cpp
- xcore/cl_image_handler.h
- xcore/cl_image_processor.cpp
- xcore/cl_image_processor.h
- xcore/drm_bo_buffer.cpp
- xcore/drm_bo_buffer.h
This is a workaround for HW encoder which only support Y plane offset = 0.
> swap-buffer: auto config init_order in cl processor

- xcore/cl_image_handler.cpp
* in some case, kernel parameters may be released before
cl kernel execution
> cl handler: fix post_execute after each kernel done

- cl_kernel/kernel_retinex.cl
- xcore/cl_retinex_handler.cpp
* default is still 2-scale retinex
* if want 3 scale, need #define XCAM_RETINEX_MAX_SCALE 3
> cl-retinex: support 3 scale gaussian

- xcore/cl_memory.cpp
- xcore/cl_memory.h
* Usage:
SmartPtr<CLBuffer> cl_buffer = new CLBuffer (
context, sizeof(uint8_t) * width * height,
CL_MEM_READ_WRITE, NULL);
CLImageDesc cl_desc = {
{CL_R, CL_UNSIGNED_INT8},
width, height,
sizeof(uint8_t) * width,
0, 0, 0 };
SmartPtr<CLImage2D> cl_image = new CLImage2D (
context, cl_desc, 0, cl_buffer);
> cl_mem: support conversion from buffer to image2d

- modules/ocl/cl_image_handler.cpp
- modules/ocl/cl_image_handler.h
- modules/ocl/cl_image_processor.cpp
- modules/ocl/cl_image_processor.h
- xcore/buffer_pool.h
* manange processor buffer sequence and only when buffer-pool is avaiable.
* add CLImageHandler::is_ready() interface to check handler status.
> cl-framework: optimize processor buffer mangement

- xcore/xcam_thread.cpp
- xcore/xcam_thread.h
* fix bug when thread invoked stop() , object may be deleted
before stopped().
bug: https://github.com/01org/libxcam/issues/401
> xcam-thread: fix crash issue when thread stopped

- modules/ocl/Makefile.am
- modules/ocl/cv_image_deblurring.cpp
- modules/ocl/cv_image_deblurring.h
- tests/Makefile.am
- tests/test-image-deblurring.cpp
Performance and quality will be improved in the next versions
> implement iterative blind deblurring algorithm

- doc/yocto/libxcam_sample.bb
- modules/interface/stitcher.h
- modules/ocl/cl_image_360_stitch.cpp
- modules/ocl/cl_image_360_stitch.h
- modules/ocl/cl_pyramid_blender.cpp
- modules/ocl/cv_feature_match.cpp
- modules/ocl/cv_feature_match.h
- tests/test-image-stitching.cpp
- wrapper/gstreamer/gstxcamfilter.h
* add 4 cameras mode
* optimize feature match to support single match at a time
* prepare parameters for each blender independently
* swap buffer index for the last blender in configuration phase
* test-image-stitching cmdline:
$ test-image-stitching --input input0.nv12 --input input1.nv12 \
--input input2.nv12 --input input3.nv12 --output output.mp4 \
--input-w 1280 --input-h 800 --output-w 4864 --output-h 1408 \
--scale-mode local --enable-fisheyemap --res-mode 1080p4 \
--fm-ocl false --framerate 30.0 --save true \
--fisheye-num 4 --all-in-one false
> cl-stitch: support multiple cameras

- plugins/smart/dvs/libdvs/stabilizer.h
The opencv2/videostab.hpp header is not indirectly included
via the opencv2/opencv.hpp header until OpenCV version 3.2+.
Thus, explicitly include opencv2/videostab.hpp so libdvs can
compile with OpenCV version 3.1.
Fixes #475
Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>
> libdvs: include opencv2/videostab.hpp

- configure.ac
- modules/ocl/cl_kernel.cpp
- modules/ocl/cl_kernel.h
patch 1: autoconfig to set minimum required opencv version
patch 2: cache cl kernel binaries into files
> opencv version check & cl kernel binary cache to files

- modules/ocl/cv_base_class.cpp
- modules/ocl/cv_base_class.h
- modules/ocl/cv_context.cpp
- modules/ocl/cv_context.h
- modules/ocl/cv_feature_match.cpp
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>
There is a bug with cv_context class cv::ocl::setUseOpenCL (_use_ocl) will always set "false" here and there is no way to change it later. This patch use cv::ocl::setUseOpenCL (cv::ocl::haveOpenCL()); instead.
> cv-context: fix bug with cv::ocl::setUseOpenCL

- modules/ocl/cv_base_class.cpp
- modules/ocl/cv_context.h
- modules/ocl/cv_feature_match.cpp
* the _cv_context redefined in constructor is local variable,
which will cause member variable is not uninitialized
> CVContext: fix duplicate definition

- modules/ocl/cl_utils.cpp
- modules/ocl/cl_utils.h
- tests/test-image-stitching.cpp
- tests/test-soft-image.cpp
- xcore/interface/data_types.h
- xcore/interface/stitcher.cpp
- xcore/interface/stitcher.h
- xcore/surview_fisheye_dewarp.cpp
- xcore/surview_fisheye_dewarp.h
- xcore/xcam_utils.cpp
- xcore/xcam_utils.h
* add BowlModel for topview and bowlview construction
- get_max_topview_area_mm (length_mm, width_mm);
- get_topview_vertex_map (
vertices, texture_points, res_width, res_height,
length_mm = 0.0f, width_mm = 0.0f);
- get_bowlview_vertex_map (vertices, texture_points, res_width, res_height);
* check test-soft-image.cpp:dump_topview_image to see how to use topview
> stitcher: add bowl model vertex

- tests/test-image-stitching.cpp
- tests/test-soft-image.cpp
- tests/test_common.h
* add environment variable FISHEYE_CONFIG_PATH for
calibration path.
* add option --save-top-view for top-view video record,
default No.
* add option --save-free-view for free-point-view video
record, default No.
* test cmdline: last-line enabled top-view and free-view.
$ export FISHEYE_CONFIG_PATH=/etc/xcam/calibration
$ ./test-image-stitching --input cam0_1280x800.nv12 \
--input cam1_1280x800.nv12 --input cam2_1280x800.nv12 \
--input cam3_1280x800.nv12 --output stitch-out.mp4 \
--input-w 1280 --input-h 800 --output-w 1920 --output-h 640 \
--scale-mode local --enable-fisheyemap --res-mode 1080p4 \
--surround-mode bowl --fm-ocl false --framerate 30.0 \
--save true --fisheye-num 4 --all-in-one false \
--save-top-view --save-free-view
> test-image-stitch: calibration data move to FISHEYE_CONFIG_PATH dir

- configure.ac
* osg changed pkgconfig install modules in a recent patch, it will no longer install openscenegraph.pc
> build: rename osg pkg_check_modules name

- tests/test_stream.h
Stream has virtual function, but the destructor is not virtual.
> Make Stream::~Stream virtual

- modules/ocl/cl_utils.cpp
* fix global scale crash issue for ocl stitching
> ocl-utils: correct row pitch for SubBuffer

- modules/soft/soft_stitcher.cpp
- tests/test-surround-view.cpp
- xcore/interface/stitcher.h
* test cmdline:
$ test-surround-view --module soft --output output.mp4 \
--input input0.nv12 --input input1.nv12 --input input2.nv12 \
--fisheye-num 3 --res-mode 8k3cams --dewarp-mode sphere \
--scale-mode dualconst --frame-mode multi --fm-mode cluster \
--in-w 3840 --in-h 2880 --out-w 7680 --out-h 3840 --save true \
--save-topview false --loop 1
> soft-stitch: support 8k(3-cameras) sphere stitching

- modules/vulkan/Makefile.am
They are not generated and are present in source directory. Leads to failures when builddir != srcdir:
| compilation terminated.
| make[3]: *** [libxcam_vulkan_la-vk_geomap_handler.lo] Error 1
| make[3]: *** Waiting for unfinished jobs....
| ../../../git/modules/vulkan/vk_copy_handler.cpp:80:10: fatal error: shader_copy.comp.spv: No such file or directory
|    80 | #include "shader_copy.comp.spv"
Signed-off-by: Anuj Mittal <anuj.mittal@intel.com>
> modules/vulkan: point to correct location of spv shaders

- tests/test-soft-image.cpp
throw compilation error:
| ../../git/tests/test-soft-image.cpp:31:10: fatal error: xcore/fisheye_dewarp.h: No such file or directory
|    31 | #include <xcore/fisheye_dewarp.h>
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~
| compilation terminated.
TEST_BASE_CXXFLAGS already includes -I$(top_srcdir)/xcore
Ref: https://github.com/intel/libxcam/blob/1.4.0/tests/Makefile.am#L48
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
> test-soft-image.cpp: fix header path

- modules/vulkan/vk_instance.cpp
1.2.140 removed the various _BEGIN_RANGE, _END_RANGE
and _RANGE_SIZE macros, see e.g.
https://gitlab.freedesktop.org/mesa/mesa/-/commit/b0cb38f36085ccee6e71b6e50cb4f094d7f03c58#b04a2be508b96c4286a9f20523ba531cd4f7176a_1050_1032
> Fix build with Vulkan 1.2.140 and later

- modules/ocl/cl_kernel.cpp
* "remove(temp_filename)" without checking the return value.
> cl-kernel: check return value of remove function

- m4/xcam-utils.m4
if the workstation cannot support avx512, let XCAM_CHECK_AVX512
report warning and continue building, insteadof error and stop
building, in order to support CI build
Signed-off-by: Tiger Meng <xiao.xi.meng@intel.com>
> support compile avx512 with non-avx512 workstation e.g. CI build

- tests/test-surround-view.cpp
- xcore/interface/stitcher.cpp
- xcore/interface/stitcher.h
Conversion is implemented by reusing geomap code, which is used at least for topview generation. New code calculates remap matrix and applies it with any supported geomap module: soft, gles or vulkan.
Usage example is provided in test-surround-view.
This pull request is part of Google Summer of Code project: https://summerofcode.withgoogle.com/projects/#4637812755791872
> Implement conversion from equirectangular projection to cubemap

- modules/gles/gl_fastmap_blender.cpp
- modules/gles/gl_geomap_handler.cpp
The IDs are only required inside the respective private namespaces, so
move it. This matches e.g. gl_blender.cpp and vk_blender.cpp.
> Fix multiple definitions of XCam::ShaderID (ODR violation)

- xcore/base/xcam_common.h
- xcore/fake_v4l2_device.h
- xcore/v4l2_device.cpp
- xcore/v4l2_device.h
- xcore/xcam_common.cpp
Use uint32_t instead of int for IOCTLs commands.
Warning log:
| ../../../git/xcore/fake_v4l2_device.h: In member function 'virtual int XCam::FakeV4l2Device::io_control(int, void*)':
| ../../../git/xcore/fake_v4l2_device.h:42:14: error: narrowing conversion of '3225441794' from 'long unsigned int' to 'int' [-Wnarrowing]
|    42 |         case VIDIOC_ENUM_FMT:
|       |              ^~~~~~~~~~~~~~~
| make[4]: *** [Makefile:685: libgstxcamsrc_la-gstxcamsrc.lo] Error 1
Signed-off-by: Naveen Saini <naveen.kumar.saini@intel.com>
> fake_v4l2_device.h: fix narrowing warning

- capi/ctxs/context_stitch.cpp
- modules/gles/Makefile.am
- modules/gles/egl/egl_base.cpp
- modules/gles/egl/egl_base.h
- modules/gles/egl/egl_utils.h
- modules/gles/gl_command.cpp
- modules/gles/gl_command.h
- modules/gles/gl_dma_buffer_handler.cpp
- modules/gles/gl_dma_buffer_handler.h
- modules/gles/gl_stitcher.cpp
- modules/gles/gl_stitcher.h
- modules/gles/gl_texture.cpp
- modules/gles/gl_texture.h
- shaders/glsl/shader_copy_ssbo_to_tex.comp.sl
- shaders/glsl/shader_copy_tex_to_ssbo.comp.sl
- shaders/glslx/Makefile.am
- tests/test-gles-handler.cpp
- tests/test-render-surround-view.cpp
- tests/test-surround-view.cpp
- xcore/base/xcam_buffer.h
- xcore/base/xcam_common.h
- xcore/video_buffer.cpp
- xcore/xcam_utils.cpp
- xcore/xcam_utils.h
DMA buffer import & export can be benefit to decoding, stitching and encoding GPU pipeline.
The processed frames passing in E2E pipeline (decoding, stitching and encoding) can be always in GPU memory. This will avoid to memory copy between CPU & GPU.
> gl-stitch: support import input dma buffer & export output dma buffer

- modules/ocl/cl_memory.h
Ubuntu 24.04 integrated OpenCL v3.0.15, this release includes several changes that affect backward compatibility:
"The CL_UNORM_INT24 enums are now properly considered extension enums for all OpenCL versions,
so applications will need to include an extension header to access this functionality."
> os-upgrade: ocl header file backward compatibility
