intel/libxcam

tests/test-cl-image.cpp
* cl beignet doesn't support RGB32
=> test: change demosaic output format to BGR32

autogen.sh, tools/pre-commit-code-style.sh
* code-style runs automatically on every commit
* first time, need run ./autogen.sh
=> code-style: add coding style auto-check on each commit

3alib/aiq3a_utils.cpp, 3alib/aiq_wrapper.cpp, xcore/buffer_pool.cpp, xcore/image_processor.cpp, xcore/image_processor.h, xcore/safe_list.h, xcore/x3a_analyzer.cpp
fix color_correction matrix reverse from aiq.
fix deadlock
fix 3alib crash
=> aiq+cl: fix color_correction matrix reverse from aiq and fix deadlock and crash

xcore/buffer_pool.cpp, xcore/buffer_pool.h, xcore/cl_3a_stats_calculator.cpp, xcore/cl_3a_stats_calculator.h, xcore/cl_image_handler.cpp, xcore/drm_bo_buffer.cpp, xcore/drm_bo_buffer.h, xcore/video_buffer.h
* Each cl feature may need the stats data for calculation
* sometimes stats info can used as scaled picture
=> stats: attached to each drm buffer

tests/test-device-manager.cpp, xcore/cl_context.cpp, xcore/cl_csc_handler.cpp, xcore/drm_display.cpp, xcore/isp_image_processor.cpp, xcore/x3a_analyzer_simple.cpp, xcore/x3a_statistics_queue.cpp, xcore/x3a_stats_pool.cpp, xcore/xcam_cpf_reader.c, xcore/xcam_mutex.h
Address critical issues reported by Klockwork static code analysis
=> fix Klocwork issues

tests/test-device-manager.cpp
* change bnr to bilateral
* add an example of CL features
=> change parameters of test-device-manager

configure.ac, tests/test-device-manager.cpp, xcore/cl_image_handler.cpp, xcore/cl_image_handler.h, xcore/cl_image_processor.cpp, xcore/cl_image_processor.h, xcore/xcam_obj_debug.h, xcore/xcam_utils.h
* add profiling macro for object
* add cl profiling info for image processor and handlers
=> profile: add cl profiling info

cl_kernel/kernel_ee.cl
* use sampler to detect edge automatically instead of coordinate in cl code.
=> refine ee kernel file to improve performance.

xcore/cl_3a_image_processor.cpp, xcore/cl_blc_handler.cpp, xcore/cl_denoise_handler.cpp, xcore/cl_image_handler.cpp
* tnr need at least 4 buffer cache, need raise
buffer pool size to 6 by default and set 8 for tnr
=> cl pipeline: fix async mode work with tnr

xcore/cl_blc_handler.cpp, xcore/cl_blc_handler.h, xcore/cl_image_bo_buffer.cpp, xcore/cl_image_bo_buffer.h, xcore/cl_memory.cpp, xcore/cl_memory.h
tiling mode of x may have different row_pitch between input and output buffers, need check carefully
=> fix tiling mode on blc and reduce mem type conversion

xcore/cl_blc_handler.cpp, xcore/cl_blc_handler.h, xcore/cl_bnr_handler.cpp, xcore/cl_bnr_handler.h, xcore/cl_csc_handler.cpp, xcore/cl_csc_handler.h, xcore/cl_dpc_handler.cpp, xcore/cl_dpc_handler.h, xcore/cl_gamma_handler.cpp, xcore/cl_gamma_handler.h, xcore/cl_macc_handler.cpp, xcore/cl_macc_handler.h, xcore/device_manager.cpp, xcore/device_manager.h
=> fix some possible leaks and warnings

configure.ac, xcore/Makefile.am, xcore/aiq_handler.cpp, xcore/aiq_handler.h, xcore/analyzer_loader.cpp, xcore/base/xcam_params.h, xcore/handler_interface.cpp, xcore/handler_interface.h, xcore/x3a_analyzer_aiq.cpp
separate ia_imaging and libxcam as discussed. now it's supposed to be used as follows.
git clone ssh://mjia@bee.sh.intel.com/git/smartcamera/ia_imaging.git
cd ia_imaging
git checkout -b v2.0_004.004 v2.0_004.004 OR git checkout -b v2.0_007.014 v2.0_007.014
make install
git clone https://github.com/dspmeng/libxcam.git
cd libxcam
./autogen.sh
./configure --prefix=/usr --enable-drm --enable-aiq --enable-gst --enable-libcl --enable-docs --enable-3alib
make && make install
=> AIQ upgrade changes

cl_kernel/kernel_hdr_lab.cl
avoid to use to much 'if' in cl file to improve code efficiency.
=> cl: refine sector algorithm of MACC.

xcore/drm_bo_buffer.cpp
I will create another pull request for stride issue after this request closed.
=> fix drm mapped failed on tiling picture

cl_kernel/kernel_retinex.cl
* improve saturation on uv plane
=> cl-retinex: correct color in uv plane

modules/ocl/cl_image_handler.cpp, modules/ocl/cl_image_handler.h, modules/ocl/cl_kernel.cpp, modules/ocl/cl_kernel.h, modules/ocl/cl_memory.cpp, modules/ocl/cl_memory.h, xcore/Makefile.am, xcore/base/xcam_defs.h, xcore/buffer_pool.h, xcore/drm_bo_buffer.cpp, xcore/image_file_handle.cpp, xcore/image_file_handle.h, xcore/xcam_buffer.cpp
* cl-kernel: build kernel from cache
* cl-handler: improve virtual functions
* xcore: add image file handle for image read/write
* support grey image and type-find attached-buf
=> framework: make multiple cl-kernel support easier in cl-image-handler

cl_kernel/kernel_gauss_lap_pyramid.cl, cl_kernel/kernel_geo_map.cl, clx_kernel/Makefile.am, modules/ocl/Makefile.am, modules/ocl/cl_blender.cpp, modules/ocl/cl_blender.h, modules/ocl/cl_geo_map_handler.cpp, modules/ocl/cl_geo_map_handler.h, modules/ocl/cl_pyramid_blender.cpp, modules/ocl/cl_pyramid_blender.h, tests/Makefile.am, tests/test-image-blend.cpp
cl-blender: enable multi-band blender
cl-geo-map: enable geometry table correction
tests: add blender and geo tests
robust: fix klocwork issue and convenient image write
=> cl-blender and geo-map enabled

tests/test-binary-kernel.cpp
* specify kernel-name which may be different from file name
* test cmdline
$ ./test-binary-kernel -i cl_kernel/kernel_defog_dcp.cl \
-o kernel_dark_channel.bin -k kernel_dark_channel
=> tests: add option kernel-name in test-binary-kernel

modules/ocl/cl_context.cpp, modules/ocl/cl_pyramid_blender.cpp, tests/test-binary-kernel.cpp, tests/test-image-blend.cpp, tests/test_common.h
cl-context: fix log size in kernel build
robust: fix potential mem-leak reported by klocwork
=> fix klocwork issues and log-size in kernel build

cl_kernel/kernel_gauss_lap_pyramid.cl, modules/ocl/cl_blender.h, modules/ocl/cl_image_handler.cpp, modules/ocl/cl_kernel.cpp, modules/ocl/cl_kernel.h, modules/ocl/cl_pyramid_blender.cpp, modules/ocl/cl_pyramid_blender.h, tests/test-image-blend.cpp, tests/test_common.h, wrapper/gstreamer/gstxcamfilter.cpp, wrapper/gstreamer/gstxcamsrc.cpp, xcore/xcam_obj_debug.h
* cl-pyr-blender: support seam find and seam mask
* debug: move test profiling macros to xcore
* ocl profiling: add kernel profiling
=> enable seam finding and mask in blender

modules/ocl/cl_3a_image_processor.cpp, modules/ocl/cl_image_handler.cpp, modules/ocl/cl_image_handler.h, modules/ocl/cl_image_processor.cpp, modules/ocl/cl_post_image_processor.cpp, modules/ocl/cl_tnr_handler.cpp, modules/ocl/cl_wavelet_denoise_handler.cpp
* process thread need check handler->is_handler_enabled to decide
next steps.
* change CLImageHandler::set_kernels_enable to enable_handler
=> cl-framework: fix hang on processor buf manager

modules/ocl/Makefile.am, modules/ocl/cl_image_360_stitch.cpp, modules/ocl/cl_image_360_stitch.h, modules/ocl/cl_multi_image_handler.cpp, modules/ocl/cl_multi_image_handler.h, tests/test-cl-image.cpp
add image stitching support
fix fisheye tests
=> add image stitching support

cl_kernel/kernel_geo_map.cl, modules/ocl/cl_fisheye_handler.cpp, modules/ocl/cl_fisheye_handler.h, modules/ocl/cl_geo_map_handler.cpp, modules/ocl/cl_geo_map_handler.h, tests/test-image-blend.cpp, tests/test-image-stitching.cpp, tests/test-video-stabilization.cpp, tests/test_inline.h
cl-geo-map: fix crash when lsc disabled
test: extract functions into test_inline.h
=> cl-geo-map: fix crash when lsc disabled

tests/test-device-manager.cpp, xcore/smartptr.h
smartptr: support class derived from RefObj
test-device-manager: fix potential string error
=>  smartptr: support class derived from RefObj

modules/soft/soft_handler.cpp, modules/soft/soft_handler.h, modules/soft/soft_image.h, modules/soft/soft_worker.cpp, modules/soft/soft_worker.h, xcore/image_handler.h, xcore/vec_mat.h, xcore/worker.h
add template soft-image 
framework: fix soft handler/worker issues
=> add template soft-image and fix soft-framework issues

modules/interface/blender.cpp, modules/interface/blender.h, modules/soft/Makefile.am, modules/soft/soft_blender.cpp, modules/soft/soft_blender.h, modules/soft/soft_image.h, xcore/file_handle.cpp, xcore/file_handle.h, xcore/image_file_handle.cpp, xcore/image_file_handle.h, xcore/vec_mat.h
module: start soft blender from guass scale 
file-handle: support file init in construction
=> module: start soft blender from guass scale 

METADATA
=> add METADATA for other tools to use

modules/soft/Makefile.am, modules/soft/soft_blender.cpp, modules/soft/soft_blender.h, modules/soft/soft_blender_tasks_priv.cpp, modules/soft/soft_blender_tasks_priv.h, modules/soft/soft_handler.cpp, modules/soft/soft_handler.h, modules/soft/soft_image.h, modules/soft/soft_video_buf_allocator.cpp, modules/soft/soft_worker.cpp, xcore/buffer_pool.cpp, xcore/buffer_pool.h, xcore/smartptr.h
* soft-blender: enable pipeline with most tasks
* soft-framework: improve soft image and fix segment fault
* buf-pool: derive from RefObj for easy usage
* smartptr: fix reference obj in polymorphism
=> imporve soft framework and add most tasks of blender

modules/soft/soft_blender.cpp, modules/soft/soft_blender_tasks_priv.cpp, modules/soft/soft_blender_tasks_priv.h, modules/soft/soft_image.h, modules/soft/soft_worker.cpp, xcore/file_handle.h, xcore/vec_mat.h
* soft-blender: support pyr_lap and fix mask errors
* soft-worker: extra thread is for status check
* xcore: extract vector/matrix operators
* soft-image: support file read/write
=> soft-blender: support pyr_lap and fix other issues

modules/interface/Makefile.am, modules/interface/geo_mapper.cpp, modules/interface/geo_mapper.h, modules/soft/Makefile.am, modules/soft/soft_blender.cpp, modules/soft/soft_blender_tasks_priv.cpp, modules/soft/soft_blender_tasks_priv.h, modules/soft/soft_geo_mapper.cpp, modules/soft/soft_geo_mapper.h, modules/soft/soft_handler.cpp, modules/soft/soft_image.h, tests/test-soft-image.cpp, xcore/video_buffer.cpp, xcore/video_buffer.h
* test-soft-image: add remap test and change blender cmdline
* geo-mapper: add interface and soft implemnetation
* soft-blender: move tasks into namespace XCamSoftTasks
* soft-image: support linear interpolation
* xcore: add valid check for video_buffer
=> add geo-mapper soft implementation and uint test

modules/interface/data_types.h, modules/ocl/cl_3a_stats_context.cpp, modules/ocl/cl_context.h, modules/ocl/cl_defog_dcp_handler.cpp, modules/ocl/cl_fisheye_handler.cpp, modules/ocl/cl_image_360_stitch.cpp, modules/ocl/cl_image_360_stitch.h, modules/ocl/cl_memory.h, modules/ocl/cl_newwavelet_denoise_handler.cpp, modules/ocl/cl_pyramid_blender.cpp, modules/ocl/cl_utils.cpp, modules/ocl/cl_utils.h, modules/ocl/cv_feature_match.cpp, modules/ocl/cv_surview_fisheye_dewarp.cpp, modules/ocl/cv_surview_fisheye_dewarp.h, modules/ocl/feature_match.cpp, modules/ocl/feature_match.h, tests/test-image-stitching.cpp, xcore/file_handle.cpp
* bowl-view: add API
* feature-match: fix errors in debug mode
* enqueue-map: fix map_flags error
* file-handle: fix by-pass error
* CLBuffer: retain buffer proxy
=> bowl-view: add API

modules/ocl/cl_video_stabilizer.cpp, xcore/image_projector.cpp, xcore/vec_mat.h
* support n-dimensional vector
* support nxn dimensional square matrix in row major order
=> xcore: rewrite vector & matrix template

modules/interface/data_types.h, modules/ocl/cl_image_360_stitch.cpp, xcore/base/xcam_defs.h, xcore/surview_fisheye_dewarp.cpp
@wujunkai166 please verify the change
=> bowl-data : change radian to angle degree

modules/soft/Makefile.am, modules/soft/soft_blender.cpp, modules/soft/soft_geo_mapper.cpp, modules/soft/soft_stitcher.cpp, modules/soft/soft_stitcher.h, tests/test-soft-image.cpp, xcore/Makefile.am, xcore/base/xcam_common.h, xcore/xcam_utils.cpp, xcore/xcam_utils.h
1. fix soft-geo-mapper out of bound
2. enable soft-sitcher, still in debug
3. add surround-view test
=> enable soft stitcher and test

modules/soft/soft_blender.cpp, modules/soft/soft_image.h, modules/soft/soft_stitcher.cpp, xcore/base/xcam_defs.h, xcore/xcam_utils.cpp, xcore/xcam_utils.h
* smooth soft-blender masks
* correct soft-stitcher idx
=> smooth soft-blender masks

modules/soft/soft_worker.cpp, tests/test-soft-image.cpp, xcore/surview_fisheye_dewarp.h, xcore/xcam_utils.cpp
* soft-stitcher: support circular process
* build: fix warnings
* fisheye-dewarp: remove useless header files
=> soft-stitcher: support circular process

modules/ocl/cv_image_deblurring.cpp, modules/ocl/cv_image_deblurring.h, modules/ocl/cv_image_process_helper.cpp, modules/ocl/cv_image_process_helper.h, modules/ocl/cv_wiener_filter.cpp
1. use mulspectrums function instead manual complex multiplication in wiener filter
2. add the opportunity to specify psf size and noise power manually
=> cv-image-deblurring update

tests/test-soft-image.cpp, xcore/interface/data_types.h, xcore/surview_fisheye_dewarp.cpp, xcore/surview_fisheye_dewarp.h, xcore/xcam_utils.cpp, xcore/xcam_utils.h
@wujunkai166 @liuyinhangx , please check, looks like quality improved.
=> stitch: add viewpoint to improve quality

modules/soft/soft_stitcher.cpp, tests/test-soft-image.cpp, xcore/interface/stitcher.cpp, xcore/interface/stitcher.h
* remove round-view slice size setting in camera info
* check test-soft-image.cpp:parse_camera_info
=> stitcher: simplify stitcher interface in camera info

tests/test-soft-image.cpp, xcore/interface/data_types.h, xcore/surview_fisheye_dewarp.cpp, xcore/surview_fisheye_dewarp.h
* viewpoint doesn't help quality improvement
=> stitcher: revert viewpoint patch

Android.mk, modules/soft/Makefile.am, modules/soft/soft_geo_mapper.cpp, modules/soft/soft_geo_tasks_priv.cpp, modules/soft/soft_geo_tasks_priv.h, xcore/interface/stitcher.cpp
*  stitcher: x direction start from 0.0 degree
* soft-geo: separate soft-geo task and handler
=> soft stitcher x direction start from 0 degreee and separate new file for soft-geo task

capi/xcam_handle.cpp, configure.ac, modules/ocl/Makefile.am, modules/ocl/cl_context.cpp, modules/ocl/cl_context.h, modules/ocl/cl_device.cpp, modules/ocl/cl_memory.cpp, modules/ocl/cl_memory.h, modules/ocl/cl_utils.cpp, modules/ocl/cl_utils.h, modules/ocl/intel/cl_intel_context.cpp, modules/ocl/intel/cl_intel_context.h, modules/ocl/intel/cl_va_memory.cpp, modules/ocl/intel/cl_va_memory.h
* disable cl_intel.h downloading
* separate cl_va_memory.h from cl_memory.h
* separate cl_intel_context.h from cl_context.h
* fix some undefined errors
=> standard-OCL: remove private dependence

tests/test-image-stitching.cpp, tests/test-soft-image.cpp
* test-soft-image: fix vector overflow issue on android
*test-image-stitching: fix performance issue
=> test-image-stitching: fix performance issue 

tests/test-image-deblurring.cpp
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>
=> add test for non-blind deblurring(Wiener)

modules/soft/soft_blender.cpp, modules/soft/soft_stitcher.cpp
* android: tune track_error for feature match
* stitcher: disable buffer dumping
=> android: tune track_error for feature match

modules/ocl/cl_image_360_stitch.cpp, modules/ocl/cl_kernel.cpp, modules/soft/soft_blender_tasks_priv.h, plugins/3a/aiq/aiq_wrapper.cpp, tests/test-device-manager.cpp, tests/test-soft-image.cpp, wrapper/gstreamer/gstxcamsrc.cpp
* aiq-build: fix header directory errors 
* test-soft-image: fix build error for cstring funcions
* cl-stitch: loop view_angle instead of list one by one 
* cl-kernel: fallback kernel cache in case $HOME not set 
* soft-blender: fix bug of array overflow
=> fix build errors and overflow issues

cl_kernel/kernel_geo_map.cl, modules/ocl/cl_fisheye_handler.cpp, modules/ocl/cl_fisheye_handler.h, modules/ocl/cl_geo_map_handler.cpp, modules/ocl/cl_geo_map_handler.h, modules/ocl/cl_image_360_stitch.cpp, modules/ocl/cv_feature_match.cpp
* Suggested output resolution for surround view is 1920*640.
* test cmd line:
./test-image-stitching --input input0.nv12 --input input1.nv12   \
--input input2.nv12 --input input3.nv12 --output output.mp4      \
--input-w 1280 --input-h 800 --output-w 1920 --output-h 640      \
--scale-mode local --enable-fisheyemap --res-mode 1080p4         \
--surround-mode bowl --fm-ocl false --framerate 30.0 --save true \
--fisheye-num 4 --all-in-one false
=> Stitching: Solve quality issues of 360 and surround view stitching.

modules/ocl/cv_feature_match.cpp, modules/ocl/cv_feature_match.h, modules/ocl/cv_feature_match_cluster.h, modules/soft/cv_capi_feature_match.cpp, modules/soft/cv_capi_feature_match.h, xcore/interface/feature_match.cpp, xcore/interface/feature_match.h
* fix "Assertion `final_overlap_width >= _config.sitch_min_width'
failed" issue
* move adjust_stitch_area() FeatureMatch to CVFeatureMatch
=> soft-stitcher: fix aborted issue

README.md, modules/ocl/cl_geo_map_handler.cpp, modules/soft/soft_geo_tasks_priv.cpp
* test-image-blend: fix aborted issue
* README: update README.md
* soft-geo: remove zigzag of image boundary
=> soft-geo: remove zigzag of image boundary

tests/test-image-stitching.cpp, tests/test-soft-image.cpp
* test-image-stitching: correct default surround mode
* soft-topview: remove dividing line
=> soft-topview: remove dividing line 

modules/soft/soft_geo_mapper.cpp, modules/soft/soft_geo_mapper.h, modules/soft/soft_geo_tasks_priv.cpp, modules/soft/soft_geo_tasks_priv.h, modules/soft/soft_stitcher.cpp, tests/test-soft-image.cpp, xcore/interface/data_types.h, xcore/interface/feature_match.cpp, xcore/interface/geo_mapper.h, xcore/interface/stitcher.cpp, xcore/interface/stitcher.h
* soft-geomap: support dualcurve scaling mode
* soft-geomap: support dualconst scaling mode
* feature-match: fix division by zero error
=> soft-geomap: support multiple scaling mode

modules/ocl/cv_context.h, modules/soft/cv_capi_feature_match.h, plugins/smart/dvs/libdvs/stabilizer.cpp
=> opencv: fix compile bug #569

modules/gles/Makefile.am, modules/gles/gl_buffer.cpp, modules/gles/gl_buffer.h, modules/gles/gl_program.cpp, modules/gles/gl_program.h, modules/gles/gl_shader.cpp, modules/gles/gl_shader.h, modules/gles/gl_video_buffer_pool.cpp, modules/gles/gl_video_buffer_pool.h
* gl-buffer: fix unmap failed issue
* gl-framework: add GLVideoBuffer and GLVideoBufferPool
* gl-framework: fix build errors
=> gl-framework: add GLVideoBuffer and GLVideoBufferPool

xcore/image_handler.cpp, xcore/image_handler.h
* default enable allocator
enable_allocator (true, 4);
=> framework: fix image-handler default allocator size

modules/vulkan/vk_copy_handler.cpp, modules/vulkan/vk_copy_handler.h, modules/vulkan/vk_descriptor.cpp, modules/vulkan/vk_device.cpp, modules/vulkan/vk_device.h, modules/vulkan/vk_pipeline.cpp, tests/test-vk-handler.cpp
* test-vk-handler: simplify code with Stream class
* vk-desc: increase pool set_size if set freed
=> test-vk-handler: simplify code with Stream class

modules/vulkan/vk_copy_handler.cpp, modules/vulkan/vk_worker.cpp, tests/test_stream.h
* vk-framework: fix random segmentation fault
* test_stream: fix usage errors of variables
=> vk-framework: fix random segmentation fault

configure.ac, modules/Makefile.am, modules/render/Makefile.am, modules/render/render_osg_camera_manipulator.cpp, modules/render/render_osg_camera_manipulator.h, modules/render/render_osg_model.cpp, modules/render/render_osg_model.h, modules/render/render_osg_shader.h, modules/render/render_osg_viewer.cpp, modules/render/render_osg_viewer.h, tests/Makefile.am, tests/test-render-surround-view.cpp
add openGL render to show the output image or video on window.
=> render: add OSG based render to show texture on window

tests/test-render-surround-view.cpp
surround view test app specify input car model name
--car model_name
=> render: add "--car" input option for render surround view test app to specify car model

configure.ac
* fix issue #597 compile error when opencl disabled
=> build: compile capi while ocl is enabled

wrapper/gstreamer/gstxcamsrc.cpp, wrapper/gstreamer/gstxcamsrc.h
* fix issue #602 build failures when enabling gstreamer
=> build: fix gstreamer wrapper build failures

modules/render/render_osg_model.cpp, modules/render/render_osg_model.h, modules/render/render_osg_viewer.cpp, modules/render/render_osg_viewer.h, tests/test-render-surround-view.cpp, xcore/image_file_handle.cpp
* render viewer support rendering gles & soft stitcher output textures
=> render: start render viewer in a separate thread

tests/test-render-surround-view.cpp
* test app test-surround-view provides saving stitcher output video function
=> test: remove save option from test-render-surround-view

.gitignore, modules/ocv/cv_utils.cpp, modules/vulkan/Makefile.am, modules/vulkan/vk_stitcher.cpp, tests/.gitignore, tests/test-render-surround-view.cpp, tests/test-surround-view.cpp
* test cmdline:
$ test-surround-view --module vulkan --output output.nv12 \
--input0 input0.nv12 --input1 input1.nv12 \
--input2 input2.nv12 --input3 input3.nv12 \
--in-w 1280 --in-h 800 --out-w 1920 --out-h 640 \
--topview-w 1280 --topview-h 720 --scale-mode singleconst \
--frame-mode multi --fm-mode default --save true --loop 1
=> vulkan-stitch: support feature match

modules/dnn/Makefile.am, modules/dnn/dnn_inference_engine.cpp, modules/dnn/dnn_inference_engine.h, modules/dnn/dnn_inference_utils.cpp, modules/dnn/dnn_inference_utils.h, modules/dnn/dnn_super_resolution.cpp, modules/dnn/dnn_super_resolution.h, tests/test-dnn-inference.cpp, xcore/vec_mat.h
test-command: ./test-dnn-inference --input xxx.jpg --model SR --model-file xxx.xml
=> dnn: add super resolution model

modules/dnn/Makefile.am, modules/dnn/dnn_inference_engine.cpp, modules/dnn/dnn_inference_engine.h, modules/dnn/dnn_inference_utils.cpp, modules/dnn/dnn_inference_utils.h, modules/dnn/dnn_object_detection.cpp, modules/dnn/dnn_semantic_segmentation.cpp, modules/dnn/dnn_semantic_segmentation.h, modules/dnn/dnn_super_resolution.h, tests/test-dnn-inference.cpp
test command:
$./test-dnn-inference --input xxx.jpg --model segment --model-file xxx.xml
=> dnn: add semantic segmentation model

modules/ocl/cl_image_360_stitch.cpp, modules/ocl/cl_image_360_stitch.h, modules/ocv/cv_feature_match.cpp, modules/ocv/cv_feature_match.h, modules/ocv/cv_feature_match_cluster.cpp, tests/test-image-stitching.cpp
fix map buffer failed issue in feature match debug mode
=> cv-feature-match: clean up OpenCL dependence

modules/soft/soft_geo_mapper.cpp, modules/soft/soft_geo_tasks_priv.cpp, modules/soft/soft_geo_tasks_priv.h, xcore/interface/geo_mapper.cpp, xcore/interface/geo_mapper.h
* increase soft geo mapper work thread count
* increase soft geo mapper work unit count
=> soft-stitch: improve soft stitcher performance

modules/soft/Makefile.am, modules/soft/soft_blender.cpp, modules/soft/soft_image.h, modules/soft/soft_stitcher.cpp, xcore/interface/geo_mapper.cpp
=> Revert "soft-stitch: performance optimization"

xcore/vec_mat.h
=> correct indentation error

modules/dnn/inference/Makefile.am, tests/Makefile.am, tests/test-render-surround-view.cpp
* export OPENVINO_IE_INC_PATH to the openvino top-level folder
* use openvino release 2020.3 lts at https://github.com/openvinotoolkit/openvino/releases/tag/2020.3.0
=> dnn: modify openvino include path in makefile

modules/gles/gl_stitcher.cpp, modules/soft/soft_stitcher.cpp, modules/vulkan/vk_blender.cpp, modules/vulkan/vk_stitcher.cpp, tests/test-surround-view.cpp, xcore/image_handler.h, xcore/smartptr.h, xcore/worker.cpp, xcore/worker.h
that will potentially lead to memory leak
=> soft-stitch: SoftStitcher object containing smart pointer to itself

shaders/glsl/shader_geomap_yuv420.comp.sl, xcore/fisheye_image_file.cpp
support “--fm-status wholeway” mode preliminarily
=> gl-stitch: support YUV420 mode

modules/dnn/inference/Makefile.am, modules/dnn/inference/dnn_inference_engine.h, tests/Makefile.am
* git clone https://github.com/openvinotoolkit/openvino.git
* git checkout -b releases/2021/3 origin/releases/2021/3
* export OPENVINO_IE_LIBS_PATH=<WORKDIR>/openvino/bin/intel64/Release/lib
* export OPENVINO_IE_INC_PATH=/usr/local/deployment_tools/
=> dnn: update dnn module to openvino version 2021/3

modules/gles/gl_video_buffer.cpp, modules/gles/gl_video_buffer.h, modules/isp/x3a_statistics_queue.cpp, modules/isp/x3a_statistics_queue.h, modules/ocl/cl_image_bo_buffer.cpp, modules/ocl/cl_image_bo_buffer.h, modules/ocl/cl_video_buffer.cpp, modules/ocl/cl_video_buffer.h, modules/soft/soft_video_buf_allocator.cpp, modules/soft/soft_video_buf_allocator.h, modules/vulkan/vk_video_buf_allocator.cpp, modules/vulkan/vk_video_buf_allocator.h, xcore/buffer_pool.cpp, xcore/buffer_pool.h, xcore/drm_bo_buffer.cpp, xcore/drm_bo_buffer.h, xcore/x3a_stats_pool.cpp, xcore/x3a_stats_pool.h
specifies a pointer to data that will be copied into the gl data store for initialization
=> gl-stitch-buffer: specifies a pointer to data that will be copied into gl data store

m4/xcam-utils.m4
=> XCAM_CHECK_AVX512 fail as warning

modules/ocv/cv_feature_match.cpp, modules/ocv/cv_feature_match.h, modules/ocv/cv_feature_match_cluster.cpp, xcore/interface/feature_match.cpp, xcore/interface/feature_match.h
ocv module: add get correspondence interface
=> add get correspondence interface

modules/soft/soft_stitcher.cpp
code scan reported unused varible issue "Never used variable 'cur_left' #655"
=> robust: fix issue #655

modules/soft/soft_stitcher.cpp, tests/test-soft-image.cpp, tests/test-surround-view.cpp, tests/test_sv_params.h, xcore/interface/data_types.h
* cam_model CamD6C8K camera tuning
* support cam_model CamC3C4k to output 4K video
* merged duplicate stitch_info and fm_config default parameters
* delete max_dst_longitude variable calculation judgment condition
=> New features, camera tuning and  merged duplicate default parameters

modules/gles/gl_stitcher.cpp, tests/test-gles-handler.cpp, tests/test-surround-view.cpp
command option:  ./test-surround-view --dma true
=> test-gl-stitch: add input & output dma buffer in test-surround-view
